#pragma once
#ifndef SPECIALITY_H
#define SPECIALITY_H

enum Specialty {
    DEFAULT,
    FRAUD, INTERNATIONAL_SCHEMES, CREATIVE_NIHILISM, SUBJECTIVE_RESEARCHES, 
    FILE_ANALIZIS, MICROMANAGMENT, APPLIED_MATERIALIZATION, SUBJECTIVISTICS, 
    MAGNETISM_AND_CLEARING 
}; 

#endif